/**
 * This file defines the root layout for the entire application.
 * It sets up the basic HTML structure, includes global styles, and wraps the application with necessary providers.
 */
import { type Metadata } from "next";
// Import Clerk components for authentication.
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
// Import fonts from next/font/google.
import { Geist, Geist_Mono } from "next/font/google";
// Import global CSS styles.
import "./globals.css";
// Import the ThemeProvider for light/dark mode functionality.
import { ThemeProvider } from "@/components/theme-provider";
// Import the Navbar component.
import Navbar from "@/components/Navbar";
// Import the Sidebar component.
import Sidebar from "@/components/Sidebar";
// Import the Toaster component for displaying notifications.
import { Toaster } from "react-hot-toast";

// Initialize the Geist Sans font with a CSS variable.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Initialize the Geist Mono font with a CSS variable.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata for the application, which is used for SEO.
export const metadata: Metadata = {
  title: "Sharehive",
  description: "Generated by create next app",
};

/**
 * The root layout component for the application.
 *
 * @param {object} props - The properties for the component.
 * @param {React.ReactNode} props.children - The child components to be rendered within the layout.
 * @returns {JSX.Element} The root layout of the application.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Wrap the entire application with the ClerkProvider for authentication context.
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <title>Sharehive</title>
        {/* Apply the font variables and antialiasing to the body. */}
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* Wrap the application with the ThemeProvider for theme management. */}
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="h-screen flex flex-col overflow-hidden">
              {/* Render the main navigation bar. */}
              <Navbar />
              <main className="flex-1 overflow-auto relative flex flex-col">
                {children}
              </main>
            </div>
            {/* Render the Toaster component for notifications. */}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
